### ISSUE TITLE
memory free ERROR @x64 train

### ISSUE THREAD

**Issue by Minotaur-CN** [luoyetx/face-alignment-at-3000fps#14]
Dear luoyetx,
 The code on your github could do memory Error when runing 'train' on building under X64 mode.

> lbp.cpp
#define FREE_MODEL(model)

That wasn't happend on running under X86 mode.

Did that happened before?
@luoyetx 

Regards!

Rui

**Comment by luoyetx** [comment]
@Minotaur-CN Did you build the project on Windows or Linux? I assume you build this on Windows. Then you should run `cmake .. -G "Visual Studio 12 2013 Win64"` and REBUILD the project. I didn't meet this error before, but I only tested the code with x86 on Windows and run the training on Linux.

**Comment by Minotaur-CN** [comment]
@luoyetx 
I did build on windows, and using either cmake .. win64 or setting up X64 mode on Visual stdio 12 2013 could happened that error, Which could not loading sufficient data to train a better model.
It usually happened after dumping 0th stage model.
The problem could happened when training a small sample under X64 mode.


Regards!
Rui

**Comment by luoyetx** [comment]
@Minotaur-CN You should use cmake to generate VS files. The error I think is may due to liblinear as the model is created by it. Currently, I have no idea where liblinear might go wrong.

**Comment by Minotaur-CN** [comment]
ok, Thanks very much!
