### ISSUE TITLE
is pupils landmark wrong in common.cpp?

### ISSUE THREAD

**Issue by flankechen** [luoyetx/face-alignment-at-3000fps#17]
in common.cpp line 210.
`  int pupils[][6] = { { 36, 37, 38, 39, 40, 41 }, { 42, 43, 44, 45, 46, 47 } };`

![figure_68_markup](https://user-images.githubusercontent.com/4598153/28312634-649f4fa8-6be6-11e7-85b6-2215e5bd5860.jpg)
but in the  [ibug dataset landmarks](https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/), pupils should be 37 to 42, and 43 to 48.

**Comment by luoyetx** [comment]
index starts from 0 in cpp code.
