### ISSUE TITLE
怎样写数据库？

### ISSUE THREAD

**Issue by vinccccho** [luoyetx/face-alignment-at-3000fps#6]
数据库是不是只要往Path_Images_train.txt和Path_Images_test.txt中写好.jpg和.pts的路径就好了？训练集大概需要多少张图片呢

**Comment by luoyetx** [comment]
参考 IBUG 上的格式

**Comment by vinccccho** [comment]
你好，我按照格式设置好了数据库，训练集有200张图片，测试图片的错误率有0.34，而且stage4比stage3的错误率还要高。是我数据库设置出了问题吗

**Comment by luoyetx** [comment]
@vinccccho 训练数据太少了，另外注意下数据的准确性

**Comment by 532741697** [comment]
run函数里面有对landmark值的读取，而且根据这些值和bbox计算得到了roi，请问咋样测试自己的无landmark值得图片呢？

**Comment by luoyetx** [comment]
@532741697 用 OpenCV 检脸得到框之后再做标点

**Comment by simon5u** [comment]
你好，我已经训练了一个模型，眼睛，眉毛和鼻子都没问题，可是嘴巴不能张开，什么原因呢？我是用prepare准备数据（以opencv提取bbox），test也用opencv提取bbox，就是不能张大嘴，不知道那里出错了。

**Comment by luoyetx** [comment]
@simon5u 还是训练数据的问题，可以尝试不用 opencv 取框，因为这样做会导致很多脸被筛掉。可以考虑的策略是按某种规则根据 68 个点来选取框，然后做训练，最后应用模型时将前面检测器的框做调整。
